---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# KSLE

<!-- badges: start -->
<!-- badges: end -->

The goal of KSLE is to ...

## Installation

You can install the development version of KSLE from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("kexiin/BIOSTAT615_KSLE")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(KSLE)

set.seed(123)
n <- 1000  # matrix size
# Some random data
M <- matrix(rnorm(n^2), n)
# Make it symmetric
A <- crossprod(M)
```

```{r}
k <- 5    # number of eigenvalues to calculate
system.time({eigen(A)})
system.time({eigen_IRAM(A, k)})
system.time({eigen_KSLE(A, k)})
```

```{r}
k <- 10    # number of eigenvalues to calculate
system.time({eigen_IRAM(A, k)})
system.time({eigen_KSLE(A, k)})
```
