# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arnoldi_Cpp <- function(A, V, H, start, n, m) {
    .Call(`_KSLE_Arnoldi_Cpp`, A, V, H, start, n, m)
}

GivensRotation_Cpp <- function(H1, sigma, m) {
    .Call(`_KSLE_GivensRotation_Cpp`, H1, sigma, m)
}

orthogonalization <- function(x, A) {
    .Call(`_KSLE_orthogonalization`, x, A)
}

truncate_and_expand_Cpp <- function(A, V, u, b1, Tm, Sm, n, m, k, tol0 = 1e-8) {
    .Call(`_KSLE_truncate_and_expand_Cpp`, A, V, u, b1, Tm, Sm, n, m, k, tol0)
}

HouseholderTransform_Cpp <- function(start, S1, V) {
    .Call(`_KSLE_HouseholderTransform_Cpp`, start, S1, V)
}

norm2 <- function(x) {
    .Call(`_KSLE_norm2`, x)
}

